# Generated by Django 5.2.6 on 2025-09-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('preparo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
